apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.20.2
networking:
  serviceSubnet: "10.100.0.0/16"
  podSubnet: "10.244.0.0/16"
apiServer:
  extraArgs:
    default-not-ready-toleration-seconds: "30"
    default-unreachable-toleration-seconds: "30" 
    cloud-provider: "aws"
controllerManager:
  extraArgs:
    node-monitor-grace-period: "16s" 
    node-monitor-period: "2s"
    pod-eviction-timeout: "30s"
    cloud-provider: "aws"
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
bootstrapTokens:
- token: "#TOKEN#"
  description: "default kubeadm bootstrap token"
  ttl: "15m"
localAPIEndpoint:
  advertiseAddress: "#MASTER_IP#"
  bindPort: 6443
