apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: "#TOKEN#"
    unsafeSkipCAVerification: true
    apiServerEndpoint: "#MASTER_IP#:6443"
nodeRegistration:
  name: "#HOSTNAME#"
  kubeletExtraArgs:
    cloud-provider: aws