apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
spec:
  ports:
  - port: 9200
    name: rest
  - port: 9300
    name: transport
  clusterIP: None
  selector:
    app: elasticsearch