apiVersion: v1
kind: Pod
metadata:
  name: service-pod
  labels:
    app: service-pod
spec:
  containers:
          - name: python
            image: kammahm/sdtd_data_processing:latest
            command: ['sleep', '3000']
