apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: ocr-service
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "kammahm/sdtd_data_processing:latest"
  imagePullPolicy: Always
  mainApplicationFile: local:///ensimag-sdtd/run_ocr_service.py
  sparkVersion: "2.4.6"
  deps:
    jars:
      - local:///opt/spark/spark-streaming-kafka-0-8-assembly_2.11-2.4.4.jar
  restartPolicy:
    type: Always
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    envVars:
      KAFKA_SERVER1: 'kaf1:9092'
      KAFKA_SERVER2: 'kaf2:9092'
      ZK_SERVER1: 'zoo1:2181'
      ZK_SERVER2: 'zoo2:2181'
    cores: 1
    memory: "512m"
    labels:
      version: 2.4.6
    serviceAccount: spark
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 2.4.6
